INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('欢欢',1,3,1,'20130105','',1,'喜欢一个人独处','boy2.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('珍珍',3,5,0,'20130805','',0,'爱搞恶作剧的小鬼','girl3.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('婷婷',1,4,0,'20130715','',1,'爱哭鼻子的小家伙','girl4.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('强强',1,4,1,'20130405','',1,'仗义的男子汉','boy3.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('倩倩',1,3,0,'20130611','',0,'容易感冒的小女孩','girl5.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('杰杰',1,4,1,'20130325','',1,'最爱发言的积极分子','boy4.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('莉莉',1,3,0,'20130705','',1,'离不开妈妈的公主','girl6.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('星星',1,3,1,'20130207','',0,'老被欺负却不哭鼻子','boy5.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('乐乐',1,3,0,'20130321','',1,'老想着回家玩','girl7.png');
INSERT INTO TBL_SINFO (S_NAME,C_ID,S_AGE,S_GENDER,S_INDATE,S_OUTDATE,S_WAY,S_DIS,S_HEAD)
VALUES('丫丫',1,3,0,'20130411','',1,'腼腆可爱的小淑女','girl8.png');
